Repository utelecon/utelecon.github.io, pull requests merged in 2024-10, with the labels that each got.

#1097 add /eccs/tutors
  src/pages/eccs/tutors.md
Labels: www.ecc

#1214 TrailingSlashIntegrationの廃止
  README.md
  astro.config.ts
  src/layouts/resolve-breadcrumb.ts
  src/lib/CopyAssetIntegration.ts
  src/lib/ExternalLinksIntegration.ts
  src/lib/TrailingSlashIntegration.ts
  src/lib/util.ts
Labels: web-development

#1134 Renewal of the top page design
  src/components/pages/Events.astro
  src/components/pages/Notice.astro
  src/pages/en/index.mdx
  src/pages/index.mdx
  src/styles/components/card.scss
  src/styles/components/top.scss
  src/styles/top.scss
Labels: web-development

#1215 パンくずリストのドキュメンテーション
  README.md
Labels: web-development

#1186 utol-en Managing Course Participants
  src/pages/en/utol/lecturers/settings/course_participants/confirm-delete.png
  src/pages/en/utol/lecturers/settings/course_participants/confirm-registration.png
  src/pages/en/utol/lecturers/settings/course_participants/confirm.png
  src/pages/en/utol/lecturers/settings/course_participants/delete.png
  src/pages/en/utol/lecturers/settings/course_participants/download-format.png
  src/pages/en/utol/lecturers/settings/course_participants/index.md
  src/pages/en/utol/lecturers/settings/course_participants/index.mdx
  src/pages/en/utol/lecturers/settings/course_participants/menu.png
  src/pages/en/utol/lecturers/settings/course_participants/operation.png
  src/pages/en/utol/lecturers/settings/course_participants/search-result.png
  src/pages/en/utol/lecturers/settings/course_participants/search.png
  src/pages/en/utol/lecturers/settings/course_participants/selected.png
  src/pages/en/utol/lecturers/settings/course_participants/upload-file.png
Labels: utol

#1158 experimental: add <YouTube /> component
  src/components/README.md
  src/components/embed/YouTube.astro
  src/pages/articles/share-policy/index.mdx
  src/pages/en/utokyo_account/mfa/initial/index.mdx
  src/pages/en/zoom/create_room/date_and_time/index.mdx
  src/pages/en/zoom/signin/index.mdx
  src/pages/good-practice/interview/irie.mdx
  src/pages/good-practice/interview/saito.mdx
  src/pages/google/drive/basic.mdx
  src/pages/google/drive/index.mdx
  src/pages/google/drive/recommendation.mdx
  src/pages/google/drive/share.mdx
  src/pages/oc/movies.mdx
  src/pages/utokyo_account/mfa/initial/index.mdx
  src/pages/zoom/signin/index.mdx
  src/pages/zoom/usage/mic_cam/index.mdx
Labels: web-development

#1211 英語版「システムの障害・メンテナンス情報に関する案内」の更新
  src/pages/en/support/service-status.md
Labels: web-development

#1013 add some system to top page
  src/pages/en/index.mdx
  src/pages/index.mdx
  src/styles/top.scss
Labels: web-development

#1218 Add: /notice/rss/
  src/pages/index.mdx
  src/pages/notice/index.mdx
  src/pages/notice/rss.mdx
  src/styles/rss_icon.scss
Labels: web-development

#1069 add /google/drive/storage
  src/pages/google/drive/storage/index.md
  src/pages/google/drive/storage/shared_drive_size1.png
  src/pages/google/drive/storage/storage1.png
Labels: www.ecc

#1040 Add /eccs/features/software/apple
  src/pages/eccs/features/software/apple.md
  src/pages/eccs/features/software/appleid-signout.png
Labels: www.ecc

#1062 add /eccs/misc/online-meeting
  src/pages/eccs/misc/online-meeting-zoom-usb-camera.png
  src/pages/eccs/misc/online-meeting.md
Labels: www.ecc

#1049 add /google/misc/backup/
  src/pages/google/misc/backup/index.md
  src/pages/google/misc/backup/index.mdx
Labels: www.ecc

#990 modify structure of utokyo_wifi/index page
  src/components/en/systems/utokyo_wifi/Apply.mdx
  src/components/en/systems/utokyo_wifi/Connect.mdx
  src/components/en/systems/utokyo_wifi/index.mdx
  src/components/ja/systems/utokyo_wifi/Apply.mdx
  src/components/ja/systems/utokyo_wifi/Connect.mdx
  src/components/ja/systems/utokyo_wifi/index.mdx
  src/pages/en/utokyo_wifi/index.mdx
  src/pages/utokyo_wifi/_IssueAccount.mdx
  src/pages/utokyo_wifi/_TroubleConnect.mdx
  src/pages/utokyo_wifi/index.mdx
  src/styles/components/lists.scss
Labels: web-development
