Repository utelecon/utelecon.github.io, pull requests merged in 2024-08, with the labels that each got.

#1099 add /eccs/defects/20180615-nfs-unicode-normalization
  src/pages/eccs/defects/20180615-nfs-unicode-normalization.md
Labels: www.ecc

#1112 Mac環境での等幅フォントについて
  src/pages/eccs/defects/20221130-osaka-monospace.mdx
Labels: www.ecc

#1063 Add /eccs/features/printing/web-upload
  src/pages/eccs/features/printing/web-upload-1.png
  src/pages/eccs/features/printing/web-upload-2.png
  src/pages/eccs/features/printing/web-upload-3.png
  src/pages/eccs/features/printing/web-upload-4.png
  src/pages/eccs/features/printing/web-upload-5.png
  src/pages/eccs/features/printing/web-upload-6.jpg
  src/pages/eccs/features/printing/web-upload.md
Labels: www.ecc

#1092 Add /eccs/misc/mac-initalize-profile
  src/pages/eccs/misc/mac-initialize-profile.md
Labels: www.ecc

#1100 add /google/assignments
  src/pages/google/assignments.md
Labels: www.ecc

#1050 add /google/misc/backup/download
  src/pages/google/misc/backup/download/backup-new01.png
  src/pages/google/misc/backup/download/backup-new02.png
  src/pages/google/misc/backup/download/backup-new03.png
  src/pages/google/misc/backup/download/backup-new04.png
  src/pages/google/misc/backup/download/backup-new05.png
  src/pages/google/misc/backup/download/index.md
Labels: www.ecc

#1053 add /google/youtube/live
  src/pages/google/youtube/index.mdx
  src/pages/google/youtube/live/index.md
Labels: www.ecc

#1081 add /utol/lecturers/surveys
  src/pages/utol/lecturers/surveys/create-question-button.png
  src/pages/utol/lecturers/surveys/create-question.png
  src/pages/utol/lecturers/surveys/create-surveys.png
  src/pages/utol/lecturers/surveys/create.mdx
  src/pages/utol/lecturers/surveys/download-format.png
  src/pages/utol/lecturers/surveys/download-result.png
  src/pages/utol/lecturers/surveys/global-settings.png
  src/pages/utol/lecturers/surveys/index.mdx
  src/pages/utol/lecturers/surveys/open-answer.png
  src/pages/utol/lecturers/surveys/result-comment.png
  src/pages/utol/lecturers/surveys/result.mdx
  src/pages/utol/lecturers/surveys/upload-comment.png
  src/pages/utol/lecturers/surveys/view-answer.png
Labels: utol

#1129 add poc implementation for bulk emergency
  README.md
  src/emergencies/.gitkeep
  src/layouts/Emergency.astro
  src/layouts/Layout.astro
Labels: web-development

#1141 update packages
  package-lock.json
  package.json
Labels: web-development

#1142 update actions
  .github/workflows/astro.yml
  .github/workflows/netlify.yml
Labels: web-development

#1144 Fix broken css in /utokyo_account/mfa/initial/
  src/components/pages/mfa/BaseTabSelectorButton.astro
Labels: web-development

#1146 fix sass deprecation
  src/layouts/Footer/Buttons.astro
  src/layouts/Footer/index.astro
  src/layouts/Header/Navigation.astro
  src/layouts/Header/index.astro
  src/layouts/Toc.astro
  src/styles/components/card.scss
  src/styles/main.scss
Labels: web-development

#1149 fix z-index collision
  src/layouts/Toc.astro
Labels: web-development

#1151 mv src/pages/assets to public/assets
  public/assets/images/UTlogo.png
  public/assets/images/_ogp.ai
  public/assets/images/favicon.png
  public/assets/images/ogp.png
Labels: web-development

#1152 use absolute path for vite resolve.alias
  astro.config.ts
Labels: web-development
